name: Build Mesa-git

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true
        type: string

jobs:
  start_building_turnip:
    runs-on: ubuntu-24.04
    env:
      BUILD_VERSION: ${{ inputs.version }}
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt update
        sudo apt install build-essential flex bison glslang-tools
        sudo apt install meson-1.5 

    - name: Execute build script
      run: bash ./turnip_builder_upstream.sh

    - name: Release "turnip"
      uses: softprops/action-gh-release@v1
      with:
        body: |
          Mesa Turnip V${{ inputs.version }}  
          Built from: https://gitlab.freedesktop.org/mesa/mesa
          
          >[!WARNING]
          > GPUs other than A830/A840 may work unstable!

          This is a build of current upstream Mesa with my GPU enablement hacks applied
          

        tag_name: mesa_v${{ inputs.version }}
        name: Mesa Turnip v${{ inputs.version }}
        files: |
           /tmp/mesa-turnip-main-V${{ inputs.version }}.zip
           /tmp/mesa-turnip-main-V${{ inputs.version }}.zip

