name: Build "turnip"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true
        type: string

jobs:
  start_building_turnip:
    runs-on: ubuntu-24.04
    env:
      BUILD_VERSION: ${{ inputs.version }}
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt update
        sudo apt install build-essential flex bison glslang-tools
        sudo apt install meson-1.5 

    - name: Execute build script
      run: bash ./turnip_builder.sh

    - name: Release "turnip"
      uses: softprops/action-gh-release@v1
      with:
        body: |
          A8XX Turnip Vulkan V${{ inputs.version }}
          Built from: https://github.com/xMaulana/mesa-tu8-A825.
          
          I didn't test this this much. Contact me on FEX (#android-wastelands) or EmuCore discord if there are any issues.

          
          >[!WARNING]
          > Please don't report issues to Mesa, PLEASE
                    
          Supported GPUs:
          * Adreno 8XX Family: 840, 830, 829, 825, 810
          * Adreno 7XX Family: any GPU supported by the upstream Turnip + 710/720 from Termux patches
          * Adreno 6XX Family: any GPU supported by the upstream Turnip
          
          GPUs other than 830/840 can have reduced performance and/or more glitches. Can't do anything about that, sorry!  
          Adreno 810 is additionally very slow, I'm not sure if you even want to use Turnip there
          
          Files:
          * gen8-a825 - A825-optimized branch (upstream MR + A825 perf tuning + hacks applied)
          
          Notes:
          * Disable DXVK_HUD if you see weird black artifacts
          * Apparently there are swizzling glitches in Eden & maybe other emulators, try increasing render scale(?)
          * Some games may require AMD/NVIDIA GPU to run and refuse to start on Qualcomm or block some features. I've included a patch to spoof as Steam Deck - use `TU_DEBUG=deck_emu`
          * GMEM rendering produces glitchy picture on A830 (write page faults), disable it with `TU_DEBUG=sysmem`. It's pretty much useless for PC emulation anyway.

        tag_name: tu_v${{ inputs.version }}
        name: Turnip A8XX v${{ inputs.version }}
        files: |
           /tmp/a8xx-gen8-a825-V${{ inputs.version }}.zip
